import { style } from '@mui/system'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="carousal" style={{height:"45vh",position:"relative",zIndex:-1 }} >
        <Image src="/img/h-11.jpg" className={styles.img} alt="home1"  layout="fill" quality={100}/>
      </div>
    </div>
  )
}
